docs(kubernetes): rewrite deploy tutorial

diff --git a/pages/deployments/deploying_to_kubernetes.md.erb b/pages/deployments/deploying_to_kubernetes.md.erb
--- a/pages/deployments/deploying_to_kubernetes.md.erb
+++ b/pages/deployments/deploying_to_kubernetes.md.erb
@@ -1,156 +1,85 @@
 # Deploying to Kubernetes
 
-This tutorial covers writing a Buildkite pipeline that build a Docker image
-then deploys to Kubernetes. You'll need to prepare your agents with the
-required package, cluster access, and Docker registry access.
-
-<%= toc %>
-
-## Preparing Your Agents
+This tutorial teaches deploying to Kubernetes. You'll need to prepare your
+agents with the required packages, cluster access, and Docker registry access
+before hand.
 
 <%= estimated_time "30 minutes" %>
 
-This step depends on your specific setup. You'll need to ensure the following:
+<%= toc %>
 
-- Agent has `docker push` access to the relevant Docker registry
-- Agent has `kubectl` access to the relevant Kubernetes cluster
-- The Kubernetes cluster has pull access to the relevant Docker registry
-- `docker` and `kubectl` installed
+## Overview
 
-Configuring access to a GCR registry and EKS cluster is different than
-configuring AWS for ECR and EKS. Setup also depends on how you've deployed your
-agents. Here's an overview for common setups.
+<%= image "final_test_pipeline.png" %>
 
-### GCP (Google Cloud Platform)
+You'll automate deploys from `master` to Kubernetes by the end of the tutorial.
 
-Setup is straight forward assuming your agents run on GCE instances, Docker images
-are hosted in a GCR, and there's a GKE cluster.
+This tutorial uses two pipelines. The first pipeline builds, tests, and pushes
+a Docker image to a registry. The second pipeline-our deploy pipeline-is
+provided a `DOCKER_IMAGE` environmentment for deployment to Kubernetes. You'll
+see how to trigger manual deployments, then link the pipelines for automated
+deployments.
 
-1. Grant GCE agents access GCR and GKE with a [service account](https://cloud.google.com/compute/docs/access/service-accounts)
-2. Grant agents `docker push` access as [described here](https://cloud.google.com/container-registry/docs/advanced-authentication)
-3. Install `gcloud`, `docker`, and `docker-compose` on agent instances
-4. Use `gcloud container clusters get-credentials` to get `kubectl` access
+This tutorial assumes:
 
-Steps 1-3 should be done outside the pipeline. Step 4 should be done in
-a [pre-command hook][hooks]. Here's a sample for `.buildkite/hooks/pre-command`:
+1. You have an existing test pipeline that pushes a Docker image to a registry
+2. You have a Kubernetes cluster authenticated to the Docker registry
+4. Agents have `kubectl` installed
+3. Agents have `kubectl` access to the Kubernetes cluster
 
-```bash
-set -eu
+<section class="Docs__note">
+  <p>
+    This setup is outside this tutorial's scope. However, you may refer to the
+    <a href="#notes">notes</a> for high level advice.
+  </p>
+</section>
 
-#
-export DOCKER_IMAGE_NAME="asia.gcr.io/buildkite-kubernetes-tutorial/app:${BUILDKITE_BUILD_NUMBER}"
+## Create the Deploy Pipeline
 
-echo '--- \:gcloud\: Setup'
+Buildkite supports multiple pipelines per project. The best practice is to use
+separate pipelines for testing and deploying.  Deploy pipelines are just
+like other pipelines except they're triggered by different events. You can use
+the [Github Deployment API](https://buildkite.com/blog/github-deployments) or
+[trigger steps](https://buildkite.com/docs/pipelines/trigger-step).
 
-gcloud config set project 'buildkite-kubernetes-tutorial'
-gcloud config set compute/zone 'asia-southeast1-a'
-gcloud config set compute/region 'asia-southeast1'
+Start by [creating a new pipline](https://buildkite.com/docs/pipelines/defining-steps)
+that uploads steps from `.buildkite/pipeline.deploy.yml`.
 
-gcloud container clusters get-credentials buildkite-tutorial
+<%= image "new_pipeline.png" %>
 
-set +eu
-```
+Now, configure the Github webhook to send deployment events.
 
-### AWS (Amazon Web Services)
+<%= image "pipeline_webhook.png" %>
 
-These steps assume agents are deployed to EC2, images are hosted on ECR, and
-there's a EKS cluster.
+Next, open the pipeline settings in Buildkite. Select "Trigger builds on deployments."
 
-1. Grant agent access to ECR and EKS API calls with an instance profile
-2. [Register the Buildkite agent IAM role with EKS](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html)
-3. [Install kubectl](https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html) on agents
-4. [Install IAM authenticator](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html) on agents
-5. Use `aws ecr get-login` to get [Docker registry access](https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html)
-6. Use `aws	update-kubeconfig` to get [kubectl access](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html)
+<%= image "pipeline_settings.png" %>
 
-Steps 1-4 should be done outside the pipeline. Steps 5 and 6 should be done
-in a [precommand hook][hooks].
-
-## Checking Preconditions
-
-You can use a [precommand hook][hooks] for checking preconditions. Here's an example:
-
-```bash
-# ./buildkite/hooks/pre-command
-
-set -eu
-
-# Existing commands from previous step
-
-echo '--- \:house_with_garden\: Dependencies'
-
-echo '$ kubectl --version'
-kubectl version --client
-
-echo '$ docker version'
-docker version
-
-echo '$ docker-compose version'
-docker-compose version
-
-echo '--- \:kubernetes\: Checking access'
-kubectl get services
-```
-
-This ensures subsequent pipelines steps proceed only if preconditions are met.
-This practice makes debugging pipelines easier (especially since version
-information is included in these commands).
-
-## Pushing the Docker image
-
-Each pipeline build should produce a unique Docker image. Use any of the
-[Buildkite environment variables][env vars] to export an environment variable
-with the full image name in the pre-command hook. Note that your Docker image
-name must fit your target registry. Here's an example for GCR:
-
-```bash
-# Add to .buildkite/hooks/pre-command
-export DOCKER_IMAGE_NAME="asia.gcr.io/buildkite-kubernetes-tutorial/app:${BUILDKITE_BUILD_NUMBER}"
-```
-
-Next, write a script to build, tag, and push the image called `script/buildkite/push`:
-
-```bash
-#!/usr/bin/env bash
-
-set -euo pipefail
-
-main() {
-	echo '--- \:docker\: Pushing'
-
-	docker-compose build app
-	docker tag buildkite/kubernetes-tutorial:latest "${DOCKER_IMAGE_NAME}"
-	docker push "${DOCKER_IMAGE_NAME}"
-}
-
-main "$@"
-```
-
-Lastly, add a pipeline step. If you're adding deploy steps into an existing
-pipeline, then be sure to use a `wait` step after all test steps or `block`
-step for manual confirmation before continuing.
+Finally, create `.buildkite/pipeline.deploy.yml`. A single step will do for now:
 
 ```yml
 steps:
-	# Previous testing step
-  - label: '\:docker\: Push'
-    command: script/buildlkite/push
+  - label: "\:rocket\: Push to \:kubernetes\:"
+    comamnd: script/buildlkite/deploy
+    concurrency: 1
+    concurrency_group: deploy/tutorial
 ```
 
-Your "push" step output should look similar to this:
+Set `concurrency` and `concurrency_group` when updating mutable state. These
+settings ensures only one step runs at a time, effectively creating a deploy
+queue.
 
-<%= image "push_step.png", size: '751x460', alt: 'Push step output' %>
+Now the pipeline is wired up. Time for the deploy step.
 
-## Deploying to Kubernetes
+## Setup the Deploy Step
 
-There are many ways to deploy to Kubernetes. We'll use the simplest method for
-creating [Kubernetes
-deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/).
-The trick is inserting the `$DOCKER_IMAGE_NAME` environment variable.  You can
-use `envsubst` as basic "templating" command before passing data to `kubectl
-apply`.
+Create a Kubernetes deployment manifest that references the `DOCKER_IMAGE`
+environment variable. `kubectl` does not interpolate environment variables out
+of the box, so you'll need a different solution. The `envsubst` command works
+well for this case. `envsubst` ("environment substitute") replaces environment
+variables from standard input. The result may be piped directly to `kubectl`.
 
-Here is sample YML manifest:
+First, You'll need a deployment YML file. Call this file `k8s/deployment.yml`:
 
 ```yml
 ---
@@ -161,7 +90,7 @@ metadata:
   labels:
     app: tutorial
 spec:
-  replicas: 1
+  replicas: 3
   selector:
     matchLabels:
       app: tutorial
@@ -172,41 +101,92 @@ spec:
     spec:
       containers:
         - name: app
-          image: "${DOCKER_IMAGE_NAME}"
+          image: "${DOCKER_IMAGE}"
           ports:
             - containerPort: 3000
 ```
 
-Now create a short script to deploy the manifest at `script/buildkite/deploy`:
+<section class="Docs__note">
+  <p>
+    Please refer to the official Kubernetes <a
+    href="https://kubernetes.io/docs/concepts/workloads/controllers/deployment/">deployment
+    documentation</a> for more information. Also note that there are multiple
+    ways to deploy applications to Kubernetes.
+  </p>
+</section>
+
+Now create a short deploy script (`script/buildkite/deploy`):
 
 ```bash
 #!/usr/bin/env bash
 
 set -euo pipefail
 
-main() {
-	echo '--- \:kubernetes\: Shipping'
+if [ -z "${DOCKER_IMAGE:-}" ]; then
+  echo "\:boom\: \$DOCKER_IMAGE missing" 1>&2
+  exit 1
+fi
 
-	envsubst < k8s/app.yml | kubectl apply -f -
-}
-
-main "$@"
+echo '--- \:kubernetes\: Shipping'
+envsubst < k8s/app.yml | kubectl apply -f -
 ```
 
-Lastly, add the step to pipeline. Set the `concurrency` and `concurrency_group`
-[options](https://buildkite.com/docs/pipelines/controlling-concurrency) to to
-prevent concurrent deploys. Here's the pipeline snippet:
+## Perform a Manual Deployment
+
+Open the deployment pipline and click "New Build". Click "Options" and provide the `DOCKER_IMAGE`.
+
+<%= image "manual_deployment.png" %>
+
+Assuming your agents have the required access, then success! :tada:
+
+<%= image "manual_deployment_success.png" %>
+
+## Automate Deployments
+
+[Trigger steps](https://buildkite.com/docs/pipelines/trigger-step) connect
+pipelines. Add a trigger step to the existing test pipeline to trigger the
+deploy pipeline. You may also filter out branches with the `branches` option
+and set environment variables. Remember to set the `DOCKER_IMAGE` environment
+variable.
+
+Add these steps to your existing `.buildkite/pipeline.yml`:
 
 ```yml
-  - label: '\:rocket\: Deploy'
-    command: script/buildkite/deploy
-    concurrency: 1
-    concurrency_group: deploy/tutorial
+  # Add a wait step to only deploy after all steps complete
+  - wait
+
+  - label: ':rocket: Deploy'
+    trigger: kubernetes-tutorial-deploy
+    branches: "master"
+    build:
+      message: "${BUILDKITE_MESSAGE}"
+      commit: "${BUILDKITE_COMMIT}"
+      branch: "${BUILDKITE_BRANCH}"
+      env:
+        # TODO: replace with your Dockage image name
+        DOCKER_IMAGE: "asia.gcr.io/buildkite-kubernetes-tutorial/app:${BUILDKITE_BUILD_NUMBER}"
 ```
 
-You're done! :rocket: Here's the finished pipeline:
+It's magic time. Push some code. :tada: Automated deployments!
 
-<%= image "final_pipeline.png", size: '735x407', alt: 'Final pipeline' %>
+<%= image "final_test_pipeline.png" %>
 
-[hooks]: https://buildkite.com/docs/agent/v3/hooks
-[env vars]: https://buildkite.com/docs/pipelines/environment-variables
+## Notes
+
+Configuring `kubectl` access depends on your infrastructure. Here's an overview
+for common senarios.
+
+If you're on GCP using agents on GCE and an GKE cluster:
+
+1. Grant GCE agents GKE access with a [service account](https://cloud.google.com/compute/docs/access/service-accounts)
+2. Install `gcloud` agent instances
+3. Use `gcloud container clusters get-credentials` to get `kubectl` access
+
+If you're on AWS using agents on EC2 and an EKS cluster:
+
+1. Grant agent access to EKS API calls with an instance profile
+2. [Register the Buildkite agent IAM role with EKS](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html)
+3. [Install kubectl](https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html) on agents
+4. [Install IAM authenticator](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html) on agents
+5. Install the AWS CLI
+6. Use `aws	update-kubeconfig` to get [kubectl access](https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html)
